language: rust
rust:
  - nightly-2019-07-19
  - nightly

os:
  - linux

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

install:
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "true" ]] | [[ "$TRAVIS_BRANCH" == "master" ]]; then
        rustup component add --toolchain $TRAVIS_RUST_VERSION clippy rustfmt;
    fi

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo doc --verbose --all --no-deps
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "true" ]] | [[ "$TRAVIS_BRANCH" == "master" ]]; then
        cargo clippy --verbose --all -- -D warnings;
        cargo fmt --verbose --all -- --check;
    fi