language: rust
rust:
  - nightly-2019-08-08
  - nightly

os:
  - linux

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

install:
  - |
    if ! hash cargo-install-update 2>/dev/null; then
        cargo install cargo-update;
    fi
  - cargo install-update --allow-no-update cargo-audit cargo-update
  - |
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]] || [[ "$TRAVIS_BRANCH" == "master" ]]; then
        rustup component add --toolchain $TRAVIS_RUST_VERSION clippy rustfmt;
    fi

script:
  - cargo audit
  - cargo build --verbose --all --all-targets
  - cargo test --verbose --all --all-targets --no-fail-fast
  - cargo doc --verbose --all --no-deps
  - |
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]] || [[ "$TRAVIS_BRANCH" == "master" ]]; then
        cargo clippy --verbose --all --all-targets -- -D warnings;
        cargo fmt --verbose --all -- --check;
    fi