[package]
name = "nova-rs"
version = "0.1.0"
authors = ["David Dubois <dexcelstraun7@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.1.0"
cgmath = { version = "0.17.0", features = ["swizzle"] }
crossbeam = "^0.7"
failure = "0.1.5"
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
log = { version = "0.4.7", features = ["std"] }
matches = "0.1.8"
path-dsl = "0.5.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.40"
spirv_cross = { version = "0.15.0", features = ["hlsl"] }
winapi = { git = "https://github.com/NovaMods/winapi-rs.git", rev = "c01b5ed6674ffbfcf5e78bf597e1f7826b9d379f", features = ["basetsd","d3d12", "d3d12sdklayers","d3d12shader","d3dcommon","d3dcompiler", "dxgi1_2", "dxgi1_3","dxgi1_4", "dxgidebug", "dxgiformat","dxgitype","handleapi","minwindef","synchapi", "unknwnbase","winbase","windef","winerror","winnt","winuser"] }

[dev-dependencies]
maplit = "1.0.1"
